export { default as HomeHero } from './hero'
export { default as HomePopularCourse } from './popular-products'
export { default as HomeFeature } from './benefits'
export { default as HomeOurMentors } from './products'
export { default as HomeNewsLetter } from './LocationSection'
